// Import types for Claude Code
import type { ClaudeExecParams } from "@/services/ai/providers/claude_code/claudeCliUtils";

declare global {
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  // Preload types
  interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
  }

  interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
  }

  interface ClaudeCodeAPI {
    chatCompletion: (params: ClaudeExecParams) => Promise<string | { __error: boolean, message: string }>;
    streamChat: (
      params: ClaudeExecParams,
      onChunk: (chunk: string) => void,
      onDone: () => void,
      onError: (error: any) => void
    ) => () => void;
  }

  interface OllamaAPI {
    checkStatus: () => Promise<boolean>;
    generateChatCompletion: (request: unknown) => Promise<any>;
    generateChatCompletionStream: (
      request: unknown,
      onChunk: (chunk: any) => void,
      onDone: () => void,
      onError: (error: any) => void,
    ) => () => void; // Returns a cancel function
  }

  interface ElectronAPI {
    claudeCode?: ClaudeCodeAPI;
    ollama: OllamaAPI; // Make ollama non-optional
  }

  interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    electronAPI: ElectronAPI; // Make electronAPI non-optional
  }
}
