import type { DBSession, DBMessage, DBToolExecution } from "@/services/db";

declare global {
  // Types for Claude Code (defined locally to avoid importing Node.js modules in renderer)
  interface ClaudeExecParams {
    messages: Array<{role: string; content: string}>;
    model?: string;
    max_tokens?: number;
    temperature?: number;
    sessionId?: string; // Add sessionId for database integration
    activeFolder?: string; // New field for the active folder path
    [key: string]: any;
  }

  interface IpcErrorObject {
    __error: true;
    name: string;
    message: string;
    stack?: string;
    _tag?: string;
    cause?: any;
  }
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  // Preload types
  interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
  }

  interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
  }

  interface ClaudeCodeAPI {
    chatCompletion: (params: ClaudeExecParams) => Promise<string | { __error: boolean, message: string }>;
    streamChat: (
      params: ClaudeExecParams,
      onChunk: (chunk: string) => void,
      onDone: () => void,
      onError: (error: any) => void
    ) => () => void;
    selectFolder: () => Promise<string | null>; // Add this method
  }

  interface OllamaAPI {
    checkStatus: () => Promise<boolean>;
    generateChatCompletion: (request: unknown) => Promise<any>;
    generateChatCompletionStream: (
      request: unknown,
      onChunk: (chunk: any) => void,
      onDone: () => void,
      onError: (error: any) => void,
    ) => () => void; // Returns a cancel function
  }

  interface DatabaseAPI {
    initDB: () => Promise<void | IpcErrorObject>;
    saveSession: (session: DBSession) => Promise<void | IpcErrorObject>;
    getSession: (sessionId: string) => Promise<DBSession | null | IpcErrorObject>;
    updateSession: (sessionId: string, updates: Partial<DBSession>) => Promise<void | IpcErrorObject>;
    saveMessage: (message: DBMessage) => Promise<void | IpcErrorObject>;
    getMessagesForSession: (sessionId: string, limit?: number, offset?: number) => Promise<DBMessage[] | IpcErrorObject>;
    saveToolCall: (toolCall: DBToolExecution) => Promise<void | IpcErrorObject>;
    updateToolCallResult: (toolCallId: string, resultJson: string, status: "executed_success" | "executed_error") => Promise<void | IpcErrorObject>;
    getToolCallsForMessage: (messageId: string) => Promise<DBToolExecution[] | IpcErrorObject>;
    getAllSessions: (options?: { limit?: number; offset?: number; sortBy?: "created_at" | "last_updated_at"; sortOrder?: "ASC" | "DESC" }) => Promise<DBSession[] | IpcErrorObject>;
  }

  interface ElectronAPI {
    claudeCode?: ClaudeCodeAPI;
    ollama: OllamaAPI; // Make ollama non-optional
    database: DatabaseAPI;
  }

  interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    electronAPI: ElectronAPI; // Make electronAPI non-optional
  }
}

export {}; // Make this file a module
