// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Import types for Claude Code
import type { ClaudeExecParams } from "@/services/ai/providers/claude_code/claudeCliUtils";

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface ClaudeCodeAPI {
  chatCompletion: (params: ClaudeExecParams) => Promise<string | { __error: boolean, message: string }>;
  streamChat: (
    params: ClaudeExecParams,
    onChunk: (chunk: string) => void,
    onDone: () => void,
    onError: (error: any) => void
  ) => () => void;
}

interface ElectronAPI {
  claudeCode?: ClaudeCodeAPI;
  ollama?: any; // Existing ollama interface
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronAPI?: ElectronAPI;
}
